# 网站配置

# 导入主题
theme: jekyll-theme-chirpy

# 设置网站语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果语言与 `_data/locales` 文件夹中的文件同名，布局语言也会更改，
# 否则布局语言将使用默认值 'en'。
lang: zh

# 设置时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

# 网站的主要标题
title: 温故而知新

# 副标题
tagline: 人生苦短, 及时行乐

# 网站描述，用于 SEO 元数据和 Atom feed
description: >-
  The process of learning and progress recording.

# 填写网站的协议和主机名，例如 'https://username.github.io'，注意不要以 '/' 结尾。
url: "https://wangyulin.blog.com/"

# GitHub 用户名
github:
  username: Mr.lin

# Twitter 用户名
twitter:
  username: Mr.lin

# 社交媒体和联系方式设置
social:
  # 网站显示的默认作者和版权所有者的名字
  name: wyl
  # 联系电子邮件
  email: wyl5728@qq.com
  # 社交媒体链接
  links:
    # 第一个元素作为版权所有者的链接
    - https://twitter.com
    - https://github.com/wangyulin
    # 取消注释以下内容以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Google 网站验证字符串
google_site_verification:

# ↑ --------------------------
# jekyll-seo-tag 设置结束

# Google Analytics ID
google_analytics:
  id:

# Goatcounter ID
goatcounter:
  id:

# 首选颜色主题设置
# 注意：保持空白将默认跟随系统颜色偏好，
# 并且侧边栏左下角会有一个切换主题的开关。
# 可用选项：
#     light  - 使用浅色主题
#     dark   - 使用深色主题
theme_mode:

# 图片的 CDN 端点
# 注意，一旦指定，CDN URL 将添加到所有以 '/' 开头的图片路径。
# 例如 'https://cdn.com'
img_cdn: "https://chirpy-img.netlify.app"

# 侧边栏头像，支持本地或跨域资源
avatar: "https://w-yl.oss-cn-chengdu.aliyuncs.com/image-20240626151740332.png"

# 网站级别社交预览图像 URL，用于 SEO `og:image` 元标签
# 可以通过自定义 `page.image` 覆盖
social_preview_image:

# 全局目录开关，布尔类型
toc: true

# 评论系统设置
comments:
  # 评论系统全局开关，例如 'disqus'。保持空白表示禁用。
  active:
  # Disqus 设置 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  disqus:
    shortname:
  # Utterances 设置 › https://utteranc.es/
  utterances:
    repo:
    issue_term:
  # Giscus 设置 › https://giscus.app
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    input_position:
    lang:
    reactions_enabled:

# 自托管静态资源设置 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔类型，保持空白表示 false
    # 指定 Jekyll 环境，空白表示两者都适用
    # 仅在 `assets.self_host.enabled` 为 'true' 时有效
    env: # [development | production]

# PWA（渐进式网页应用）设置
pwa:
  enabled: true # PWA 功能选项（可安装）
  cache:
    enabled: true # PWA 离线缓存选项
    # 这里定义的路径将被排除在 PWA 缓存之外。
    # 通常其值是与当前网站共享相同域名的另一个网站的 `baseurl`。
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URL 将不会被 PWA 缓存

# 每页显示的文章数量
paginate: 10

# 站点基础 URL
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

# Kramdown 设置
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 选项 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Jekyll 集合设置
collections:
  tabs:
    output: true
    sort_by: order

# 默认设置
defaults:
  - scope:
      path: "" # 这里的空字符串表示项目中的所有文件
      type: posts
    values:
      layout: post
      comments: true # 启用文章评论。
      toc: true # 在文章中显示目录。
      # 除非非常有把握，否则不要修改以下参数
      # 否则需要更新项目中所有其他文章链接的代码。
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 参见 `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Sass 压缩样式
sass:
  style: compressed

# HTML 压缩设置
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# 排除的文件和目录
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

# Jekyll 归档插件设置
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
